### ISSUE TITLE
Submission :Transferring the competition to the new website

### ISSUE THREAD

**Issue by pencilYi** [oxuva/long-term-tracking-benchmark#9]
I found that submission upload on the old site has been disabled. But I can not find the competition in the new site. According to the developer of CodaLab, transferring a competition to the new website is quick and easy for the organizers. I'm appreciate it if you can migrate the competition to the new site!

**Comment by pencilYi** [comment]
@jvlmdr @bertinetto

**Comment by Tchuanm** [comment]
Hi, For now, I still cannnot find the challenge in new website. Do you have any idea?
